### PR TITLE
fix ISE in cluster version detection

### LINKED ISSUE #519: No fallback when OCP version does not match
In case no matching OCP version was found for the client download in [ClusterVersionInfo](https://github.com/xtf-cz/xtf/blob/master/core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java#L24-L25) some fallback is expected to be executed to download the OpenShift client binary. E.g. in case no matching OCP version `4.12.0-ec.5` was used the path resolver failed with error

```
WARN - Version 4.12.0-ec.5 configured in xtf.openshift.version isn't in expected format 'major.minor[.micro]'.
[2022-11-15 11:12:52,114] ERROR- Failed to install operator
java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)
	at cz.xtf.core.openshift.ClusterVersionInfo.isMajorMinorMicro(ClusterVersionInfo.java:73)
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.getVersionOrChannel(ClusterVersionOpenShiftBinaryPathResolver.java:236)
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.getClientUrlBasedOnOcpVersion(ClusterVersionOpenShiftBinaryPathResolver.java:81)
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.determineClientUrl(ClusterVersionOpenShiftBinaryPathResolver.java:42)
	at cz.xtf.core.openshift.ClusterVersionOpenShiftBinaryPathResolver.resolve(ClusterVersionOpenShiftBinaryPathResolver.java:32)
	at cz.xtf.core.openshift.OpenShiftBinaryManagerFactory.getOpenShiftBinaryManager(OpenShiftBinaryManagerFactory.java:19)
	at cz.xtf.core.openshift.OpenShifts.getBinaryPath(OpenShifts.java:77)
	at com.redhat.xpaas.eap.util.OpenShiftBinaryClient.<init>(OpenShiftBinaryClient.java:26)
	at com.redhat.xpaas.eap.util.OpenShiftBinaryClient.getInstance(OpenShiftBinaryClient.java:32)
	at com.redhat.xpaas.eap.operator.junit.listener.OperatorInstaller.installOperator(OperatorInstaller.java:552)
	at com.redhat.xpaas.eap.operator.junit.listener.OperatorInstaller.testPlanExecutionStarted(OperatorInstaller.java:131)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$testPlanExecutionStarted$12(TestExecutionListenerRegistry.java:115)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.lambda$notifyEach$1(TestExecutionListenerRegistry.java:67)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyEach(TestExecutionListenerRegistry.java:65)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$200(TestExecutionListenerRegistry.java:32)
	at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.testPlanExecutionStarted(TestExecutionListenerRegistry.java:115)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:53)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

### PR DESCRIPTION
**Pull request by simkam**
fixes #519 

supersedes #541

Please make sure your PR meets the following requirements:
- [x] Pull Request contains a description of the changes
- [x] Pull Request does not include fixes for multiple issues/topics
- [x] Code is formatted, imports ordered, code compiles and tests are passing
- [x] Code is self-descriptive and/or documented

### CODE REVIEW

File: core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java [hunk 1]
```diff
@@ -69,14 +70,21 @@ boolean isMajorMinorOnly() {
...
     }
 
+    /**
+     * Check if version is nightly / developer version. It is badly named because anything in
+     * x.y.z-abc is considered nightly.
+     *
+     * @return true, if the version is nightly/developer. Meaning in x.y.z-abc format.
+     * @deprecated There is no replacement, but it can change because of bad name.
+     */
     boolean isNightly() {
```
Comment (laDok8) [inline core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java:86]: I favor removing (or renaming) this method as it no longer makes sense. Now it can be basically substituted by  `!isMajorMinor && !isMajorMinorMicro`

File: core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java [hunk 2]
```diff
@@ -21,8 +21,9 @@
 @Slf4j
 public class ClusterVersionInfo {
     // version must be in format major.minor.micro (4.8.13) or major.minor (4.8)
-    private static final Pattern versionPattern = Pattern
-            .compile("^(\\d+\\.\\d+)(\\.\\d+)?(-\\d+\\.nightly-\\d{4}-\\d{2}-\\d{2}-\\d{6})?$");
+    // consider any version after with 'x.y.z-abc' as nightly/developer build
+    // nightly in context of this class to not to change API
+    private static final Pattern versionPattern = Pattern.compile("^(\\d+\\.\\d+)(\\.\\d+)?(-.*)?$");
```
Comment (laDok8) [inline core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java:26]: There may be a problem as all non-standard versions are detected as dev-preview e.g. it will fail to download [4.7.0-rc.3](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.7.0-rc.3/), which is in the classic stream.
Furthermore e.g. `99.99.99` is detected as a valid version, but that's happening even without this PR so I suppose that's expected behavior

Comment (simkam) [reply core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java:27]: ok, updated, it leverages new `isDeveloperPreview()` method and added more tests

File: core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java [hunk 3]
```diff
@@ -69,15 +70,32 @@ boolean isMajorMinorOnly() {
...
+            return Optional.ofNullable(versionMatcher.group(3)).orElse("").contains("-rc.");
+        }
+        return false;
+    }
+
+    /**
+     * Check if version is release candidate. Version in x.y.z-rc... format
+     *
+     * @return true if version contains -rc. string
+     */
```
Comment (laDok8) [inline core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java:95]:
```suggestion
    /**
     * @return true if the version should be searched in dev-preview
     */
```

Comment (simkam) [reply core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java:95]: well, `ClusterVersionInfo` doesn't really know how this method will be used. That it will be used to determine client URL. It could be used on more places, despite its package private scope.

Comment (laDok8) [reply core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java:95]: understandable, anyway it could use some fix `@return true if version contains -rc. string` is not correct

Comment (simkam) [reply core/src/main/java/cz/xtf/core/openshift/ClusterVersionInfo.java]: should be fixed now

**Review by laDok8 — COMMENTED** [review]
LGTM

**Comment by mnovak1** [comment]
@simkam Can we have any CI runs like in https://github.com/xtf-cz/xtf/pull/541#issuecomment-1582416570 ?

**Comment by simkam** [comment]
- detected from cluster - 4.13.3 -- [eap-8.x-openshift-4-80-openjdk17/247/](https://jenkins.eapqe.psi.redhat.com/job/eap-8.x-openshift-4-80-openjdk17/247/) :heavy_check_mark: 
  ```
  [2023-06-28 11:11:17,534] DEBUG- Trying to determine OpenShift client url for cluster version 4.13.3.
  [2023-06-28 11:11:17,612] DEBUG- Trying to load OpenShift client archive from cache (enabled: true) or download it from https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/4.13.3/openshift-client-linux.tar.gz.
  [2023-06-28 11:11:17,615] DEBUG- OpenShift client archive not found in cache, downloading it.
  ```
- detected from cluster - 4.14.0-ec.1 -- [eap-8.x-openshift-4-80-openjdk17/248/](https://jenkins.eapqe.psi.redhat.com/job/eap-8.x-openshift-4-80-openjdk17/248/) :heavy_check_mark: 
  ```
  [2023-06-28 11:11:51,524] DEBUG- Trying to determine OpenShift client url for cluster version 4.14.0-ec.1.
  [2023-06-28 11:11:51,595] DEBUG- Trying to load OpenShift client archive from cache (enabled: true) or download it from https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp-dev-preview/4.14.0-ec.1/openshift-client-linux.tar.gz.
  [2023-06-28 11:11:51,599] DEBUG- OpenShift client archive not found in cache, downloading it.
  ```
- manually added by `-Dxtf.openshift.version=4.9.0-rc.3` - client not available at mirror.openshift.com - default to configured channel -- [eap-8.x-openshift-4-80-openjdk17/249/](https://jenkins.eapqe.psi.redhat.com/job/eap-8.x-openshift-4-80-openjdk17/249/) :heavy_check_mark: 
  ```
  [2023-06-28 11:12:16,093] DEBUG- Trying to determine OpenShift client url for cluster version 4.9.0-rc.3.
  [2023-06-28 11:12:16,647] DEBUG- Trying to load OpenShift client archive from cache (enabled: true) or download it from https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/stable/openshift-client-linux.tar.gz.
  [2023-06-28 11:12:16,652] DEBUG- OpenShift client archive not found in cache, downloading it. 
  ```  
- manually added by `-Dxtf.openshift.version=4.9.0-rc.7` - client available -- [eap-8.x-openshift-4-80-openjdk17/250/](https://jenkins.eapqe.psi.redhat.com/job/eap-8.x-openshift-4-80-openjdk17/250/) :heavy_check_mark: 
  ```
  [2023-06-28 11:29:35,155] DEBUG- Trying to determine OpenShift client url for cluster version 4.9.0-rc.7.
  [2023-06-28 11:29:35,672] DEBUG- Trying to load OpenShift client archive from cache (enabled: true) or download it from https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/4.9.0-rc.7/openshift-client-linux.tar.gz.
  [2023-06-28 11:29:35,675] DEBUG- OpenShift client archive not found in cache, downloading it.

  ```

**Review by mnovak1 — APPROVED** [review]

**Comment by mnovak1** [comment]
@simkam thanks, merging.
